name: Bug Report
description: File a bug report.
title: "[Bug]: <title>"
labels: ["Bug", "Needs Triage"]
body:
  - type: markdown
    attributes:
      value: |
        Hello! Thanks for supporting LatentEye and taking the time to fill out this information! It helps me a lot.
  - type: dropdown
    id: bugtype
    attributes:
      label: I'm submitting...
      options:
        - a bug report.
        - a failure with a generated image.
        - a performance problem. Don't worry I won't tell.
        - something else?
  - type: dropdown
    id: ostype
    attributes:
      label: I'm seeing the problem on?
      multiple: true
      options:
        - MacOS - Intel
        - MacOS - Apple Silicon
        - Linux
        - Windows        
  - type: markdown
    attributes:
      value: |
        in the report please let me know what OS version or Linux distro and version you are using.
  - type: dropdown
    id: pyversion
    attributes:
      label: I'm using python version. 
      multiple: true
      options:
        - Python 3.10
        - Python 3.12
        - Python 3.13
        - a version later then 3.13
        - a version EARLIER than 3.10
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: What happened?
      description: what did you expect to happen?
      placeholder: Tell us what happened in as much relevant detail as possible. 
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What you expected to happen?
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: image
    attributes:
      label: Problem Image
      description: | 
        If applicable, add image files that LatentEye couldn't see or any screenshots to help explain your problem. Please ensure your image has metadata.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: |
        ![DESCRIPTION](LINK.png)
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? system info? Anything that will give us more context about the issue you are encountering!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
