---
name: "\U0001F680 Feature Request"
about: "I have an idea (and may want to implement it \U0001F642)!"
# title: ''
labels: "enhancement, needs triage"
---

Thanks for taking the time to share your vision for a LatentEye new feature.

## Feature Request

**Is your feature request related to a problem**
If so, please provide the bug number[...]

**Describe the solution you would  like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Additional Context**
Add any other context or images about the feature request here
